# Generated by Django 4.2.23 on 2026-06-23 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='post_gallery/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='blog.post')),
            ],
        ),
    ]
