# Generated by Django 4.2.23 on 2026-06-24 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='second_image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
