# Generated by Django 4.2.23 on 2026-06-25 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_second_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
